version: "3"
services:
  cfml:
    container_name: cf9-test
    image: ortussolutions/commandbox:3.9.0
    restart: always
    environment:
      PORT: 80
    volumes:
      - "./:/app"
    ports:
      - 127.0.0.1:80:80
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 1m30s
      timeout: 5s
      retries: 10
      start_period: 25s

networks:
  backend:
    driver: bridge